import { useEffect } from "react"
import { loginWithGithub } from "@firebase/client"
import Head from "next/head"
import { useRouter } from "next/router"

import Logo from "@components/Icons/Logo"
import useUser, { USER_STATES } from "@hooks/useUser"
import { Loader } from "@components/Loader"
import ActionButton from "@components/Buttons/ActionButton"
import GitHub from "@components/Icons/GitHub"

import { colors, fonts } from "@styles/theme"
import { addOpacityToColor } from "@styles/utils"

export default function HomePage() {
  const user = useUser()
  const router = useRouter()

  const handleClick = () => {
    loginWithGithub()
  }

  useEffect(() => {
    user && router.replace("/home")
  }, [user])

  return (
    <>
      <Head>
        <title>Devtter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section>
        <Logo heigth={120} width={120} fill={colors.primary} />
        <h1 className="title">Welcome to Devtter!</h1>
        <h2>The social media from developers to developers</h2>
        <div className="auth-status-container">
          {user === USER_STATES.NOT_LOGGED && (
            <div>
              <ActionButton
                onClick={() => handleClick()}
                styles={`font-weight: 500;  font-family: ${fonts.base};`}
              >
                <GitHub width={16} heigth={16} />
                Sign in with GitHub
              </ActionButton>
            </div>
          )}
          {user === USER_STATES.NOT_KNOWN && <Loader />}
        </div>
      </section>

      <style jsx>{`
        .auth-status-container {
          margin-top: 16px;
        }
        .main {
          height: 100%;
        }
        h1 {
          text-align: center;
          font-size: 32px;
          font-weight: 800;
          color: ${colors.primary};
          margin: 0;
        }
        h2 {
          font-family: ${fonts.secondary};
          text-align: center;
          font-size: 18px;
          color: ${addOpacityToColor(colors.black, 0.8)};
          margin: 0;
        }
        section {
          display: grid;
          place-items: center;
          place-content: center;
          height: 100%;
        }
      `}</style>
    </>
  )
}
