import { useEffect } from "react"
import { loginWithGithub } from "@firebase/client"
import Head from "next/head"
import { useRouter } from "next/router"

import GitHubButton from "@components/Buttons/GitHubButton"
import Logo from "@components/Icons/Logo"
import useUser, { USER_STATES } from "@hooks/useUser"

import { colors } from "@styles/theme"
import { addOpacityToColor } from "@styles/utils"
import { Loader } from "@components/Loader"

export default function Home() {
  const user = useUser()
  const router = useRouter()

  const handleClick = () => {
    loginWithGithub()
  }

  useEffect(() => {
    user && router.replace("/home")
  }, [user])

  return (
    <div className="main">
      <Head>
        <title>Devtter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section>
        <div className="logo">
          <Logo />
        </div>
        <h1 className="title">Welcome to Devtter!</h1>
        <h2>The social media from developers to developers</h2>
        <div className="auth-status-container">
          {user === USER_STATES.NOT_LOGGED && (
            <div>
              <GitHubButton onClick={() => handleClick()} />
            </div>
          )}
          {user === USER_STATES.NOT_KNOWN && <Loader />}
        </div>
      </section>

      <style jsx>{`
        .auth-status-container {
          margin-top: 16px;
        }
        .main {
          height: 100%;
        }
        .logo {
          width: 120px;
        }
        h1 {
          text-align: center;
          font-size: 32px;
          font-weight: 800;
          color: ${colors.primary};
          margin: 0;
        }
        h2 {
          text-align: center;
          font-size: 16px;
          color: ${addOpacityToColor(colors.secondary, 0.8)};
          margin: 0;
        }
        section {
          display: grid;
          place-items: center;
          place-content: center;
          height: 100%;
        }
      `}</style>
    </div>
  )
}
